project_id = "yanjhfqqdcevlzmwsrnj"

[functions.delete-account]
verify_jwt = true

[functions.verify-purchase]
verify_jwt = false

[functions.scheduled-notifications]
verify_jwt = false

[functions.send-push]
verify_jwt = false
