-- Insert Orthodox Calendar Days for 2026
INSERT INTO public.orthodox_calendar_days (year, month, day_number, description, color)
VALUES
-- January 2026
(2026, 1, 1, '(†) Tăierea-împrejur cea după trup a Domnului; †) Sf. Ier. Vasile cel Mare, arhiep. Cezareei Capadociei și mama sa Sf. Emilia', 'red'),
(2026, 1, 2, 'Înainte-prăznuirea Botezului Domnului; Sf. Ier. Silvestru, ep. Romei; Sf. Cuv. Serafim de Sarov;', 'black'),
(2026, 1, 3, 'Sf. Prooroc Maleahi; Sf. Mc. Gordie', 'black'),
(2026, 1, 4, 'Soborul Sf. 70 de Apostoli; Sf. Cuv. Teoctist din Siciliei; Sf. Cuv. Apolinaria; Sf. Cuv. Nichifor cel Lepros', 'red'),
(2026, 1, 5, 'Sf. Mc. Teopempt și Teonas; Sf. Cuv. Sinclitichia', 'black'),
(2026, 1, 6, '(†) Botezul Domnului (Boboteaza - Dumnezeiasca Arătare)', 'red'),
(2026, 1, 7, '† Soborul Sf. Prooroc Ioan Botezătorul și Înaintemergătorul Domnului', 'red'),
(2026, 1, 8, 'Sf. Cuv. Gheorghe Hozevitul; Sf. Cuv. Domnica', 'black'),
(2026, 1, 9, 'Sf. Mc. Polieuct; Sf. Ier. Petru, ep. Sevastiei', 'black'),
(2026, 1, 10, 'Sf. Ier. Grigorie, ep. Nyssei; †) Sf. Cuv. Antipa de la Calapodești; Sf. Ier. Dometian, ep. Melitenei;', 'black'),
(2026, 1, 11, '† Sf. Cuv. Teodosie, începătorul vieții călugărești de obște din Palestina; Sf. Cuv. Vitalie', 'red'),
(2026, 1, 12, 'Sf. Mc. Tatiana diaconița și Eutasia', 'black'),
(2026, 1, 13, '† Sf. Mc. Ermil și Stratonic; Sf. Ier. Iacob, ep. din Nisibe;', 'black'),
(2026, 1, 14, 'Odovania praznicului Botezului Domnului; Sf. Cuv. Mc. din Sinai și Rait; Sf. Nina, luminătoarea Georgiei;', 'black'),
(2026, 1, 15, 'Sf. Cuv. Pavel Tebeul și Ioan Colibașul', 'black'),
(2026, 1, 16, 'Cinstirea lanțului Sf. Ap. Petru; Sf. Mc. Danact citețul', 'black'),
(2026, 1, 17, '†) Sf. Cuv. Antonie cel Mare; Sf. Cuv. Antonie cel nou de la Veria', 'black'),
(2026, 1, 18, '† Sf. Ier. Atanasie și Chiril, arhiep. Alexandriei', 'red'),
(2026, 1, 19, 'Sf. Cuv. Macarie cel Mare și Macarie Alexandrinul;Sf. Ier. Marcu, mitr. Efesului; Sf. Mc. Eufrasia', 'black'),
(2026, 1, 20, '†) Sf. Cuv. Eftimie cel Mare; Sf. Mc. Eusebiu; † Sf. Mc. In, Pin și Rim;', 'black'),
(2026, 1, 21, 'Sf. Cuv. Maxim Mărt.; Sf. Mc. Neofit; Sf. Mc. Agnia din Roma', 'black'),
(2026, 1, 22, 'Sf. Ap. Timotei; Sf. Cuv. Mc. Anastasie Persul', 'black'),
(2026, 1, 23, 'Sf. Sfințit Mc. Clement, ep. Ancirei; Sf. Mc. Agatanghel; Sf. Părinți de la Sinodul al VI-lea Ecumenic', 'black'),
(2026, 1, 24, 'Sf. Cuv. Xenia din Roma; Sf. Xenia din Sankt Petersburg', 'black'),
(2026, 1, 25, '†) Sf. Ier. Grigorie Teologul, arhiep. Constantinopolului; †) Sf. Ier. Bretanion, ep. Tomisului', 'red'),
(2026, 1, 26, '†) Sf. Ier. Iosif cel Milostiv, mitr. Moldovei; Sf. Cuv. Xenofont, Maria, Arcadie și Ioan', 'black'),
(2026, 1, 27, '† Aducerea moaștelor Sf. Ier. Ioan Gură de Aur; Sf. Marciana, împ.', 'black'),
(2026, 1, 28, 'Sf. Cuv. Efrem Sirul, Isaac Sirul, Paladie și Iacob Sihastrul', 'black'),
(2026, 1, 29, 'Aducerea moaștelor Sf. Sfințit Mc. Ignatie Teoforul; Sf. Mc. Filotei', 'black'),
(2026, 1, 30, '†) Sf. Trei Ierarhi: Vasile cel Mare, Grigorie Teologul și Ioan Gură de Aur; Sf. Sfințit Mc. Ipolit, ep. Romei', 'red'),
(2026, 1, 31, 'Sf. Doctori fără de arginți Chir și Ioan', 'black'),
-- February 2026
(2026, 2, 1, 'Înainte-prăznuirea Întâmpinării Domnului; Sf. Mc. Trifon; Sf. Mc. Perpetua și Felicitas', 'red'),
(2026, 2, 2, '(†) Întâmpinarea Domnului (Stratenia); Evrei VII, 7-17', 'red'),
(2026, 2, 3, 'Sf. și Dreptul Simeon, primitorul de Dumnezeu; Sf. Proorociță Ana', 'black'),
(2026, 2, 4, 'Sf. Cuv. Isidor Pelusiotul; Sf. Sfințit Mc. Avramie', 'black'),
(2026, 2, 5, 'Sf. Mc. Agata și Teodula', 'black'),
(2026, 2, 6, 'Sf. Ier. Vucol, ep. Smirnei și Fotie, patr. Constantinopolului; Sf. Cuv. Varsanufie cel Mare și Ioan din Gaza', 'black'),
(2026, 2, 7, 'Sf. Ier. Partenie, ep. Lampsacului; Sf. Cuv. Luca din Elada', 'black'),
(2026, 2, 8, 'Sf. M. Mc. Teodor Stratilat; Sf. Proroc Zaharia', 'red'),
(2026, 2, 9, 'Odovania Praznicului Întâmpinării Domnului; Sf. Mc. Nichifor', 'black'),
(2026, 2, 10, '†) Sf. Sfințit Mc. Haralambie; Sf. Mc. Valentina', 'black'),
(2026, 2, 11, 'Sf. Sfințit Mc. Vlasie, ep. Sevastiei; Sf. Teodora, împ.', 'black'),
(2026, 2, 12, 'Sf. Ier. Meletie, arhiep. Antiohiei celei Mari; Sf. Mc. Hristea', 'black'),
(2026, 2, 13, 'Sf. Cuv. Martinian; Sf. Ap. și Mc. Acvila și soția sa, Priscila; Sf. Ier. Evloghie, patr. Alexandriei', 'black'),
(2026, 2, 14, 'Sf. Cuv. Auxenție, Maron și Avraam', 'black'),
(2026, 2, 15, 'Sf. Ap. Onisim; Sf. Mc. Maior', 'red'),
(2026, 2, 16, 'Sf. Mc. Pamfil preotul și Valent diaconul; Sf. Ier. Flavian, arhiep. Constantinopolului', 'black'),
(2026, 2, 17, 'Sf. M. Mc. Teodor Tiron; Sf. Mariamna; Sf. Împ. Marcian și Pulheria', 'black'),
(2026, 2, 18, 'Sf. Ier. Leon cel Mare, ep. Romei', 'black'),
(2026, 2, 19, 'Sf. Ap. Arhip, Filimon și soția sa, Apfia', 'black'),
(2026, 2, 20, 'Sf. Ier. Leon, ep. Cataniei; Sf. Cuv. Visarion', 'black'),
(2026, 2, 21, 'Sf. Cuv. Timotei; Sf. Ier. Eustatie, arhiep. Antiohiei', 'black'),
(2026, 2, 22, 'Aflarea moaștelor Sf. Mc. din Constantinopol', 'red'),
(2026, 2, 23, 'Sf. Sfințit Mc. Policarp, ep. Smirnei; Sf. Cuv. Gorgonia', 'black'),
(2026, 2, 24, '† Întâia și a doua aflare a Capului Sf. Ioan, Înaintemergătorul și Botezătorul Domnului; †) Sf. Cuv. Petroniu de la Prodromu', 'black'),
(2026, 2, 25, 'Sf. Ier. Tarasie, patr. Constantinopolului', 'black'),
(2026, 2, 26, 'Sf. Ier. Porfirie, ep. Gazei; Sf. Mc. Fotini Samarineanca', 'black'),
(2026, 2, 27, 'Sf. Cuv. Mărt. Procopie și Talaleu', 'black'),
(2026, 2, 28, '†) Sf. Cuv. Ioan Casian Romanul și Gherman din Dobrogea; Sf. Cuv. Vasile Mărt.', 'black'),
-- March 2026
(2026, 3, 1, 'Sf. Cuv. Mc. Evdochia; Sf. Cuv. Domnina', 'red'),
(2026, 3, 2, 'Sf. Sfințit Mc. Teodot, ep. Chiriniei; Sf. Mc. Isihie', 'black'),
(2026, 3, 3, 'Sf. Mc. Eutropie, Cleonic și Vasilisc', 'black'),
(2026, 3, 4, 'Sf. Cuv. Gherasim de la Iordan; Sf. Mc. Pavel și sora sa, Iuliana', 'black'),
(2026, 3, 5, 'Sf. Mc. Conon din Isauria și Conon Grădinarul; Sf. Cuv. Marcu Pustnicul', 'black'),
(2026, 3, 6, 'Sf. 42 de Mc. din Amoreea; Aflarea Sfintei Cruci', 'black'),
(2026, 3, 7, 'Sf. Sfințiți Mc. Vasilevs, Evghenie, Capiton, Eterie, Agatodor și Elpidie, ep. din Herson; † Sf. Sfințit Mc. Efrem, ep. Tomisului', 'black'),
(2026, 3, 8, '†) Sf. Pr. Mc. Liviu-Galaction de la Cluj; Sf. Ier. Mărt. Teofilact, ep. Nicomidiei', 'red'),
(2026, 3, 9, '† Sf. 40 de Mc. din Sevastia', 'black'),
(2026, 3, 10, 'Sf. Mc. Codrat, Ciprian, Dionisie și cei împreună cu ei', 'black'),
(2026, 3, 11, 'Sf. Ier. Sofronie, patr. Ierusalimului', 'black'),
(2026, 3, 12, 'Sf. Cuv. Teofan Mărt. Sf. Ier. Grigorie Dialogul, ep. Romei; Sf. Cuv. Simeon Noul Teolog', 'black'),
(2026, 3, 13, 'Aducerea moaștelor Sf. Ier. Nichifor, patr. Constantinopolului', 'black'),
(2026, 3, 14, 'Sf. Cuv. Benedict de Nursia; Sf. Sfințit Mc. Alexandru, pr. din Pidna', 'black'),
(2026, 3, 15, 'Sf. Mc. Agapie și Plisie, Timolau', 'red'),
(2026, 3, 16, 'Sf. Mc. Sabin Egipteanul; Sf. Cuv. Hristodul din Patmos', 'black'),
(2026, 3, 17, 'Sf. Cuv. Alexie, omul lui Dumnezeu', 'black'),
(2026, 3, 18, 'Sf. Ier. Chiril, arhiep. Ierusalimului', 'black'),
(2026, 3, 19, 'Sf. Mc. Hrisant și Daria, Claudiu și Ilaria; Sf. Mc. Marian diac.', 'black'),
(2026, 3, 20, 'Sf. Cuv. Mc. uciși în M. Sf. Sava cel Sfințit', 'black'),
(2026, 3, 21, 'Sf. Ier. Iacob Mărt.; Sf. Cuv. Serapion;', 'black'),
(2026, 3, 22, 'Sf. Sfințit Mc. Vasile, pr. din Ancira; Sf. Mc. Drosida, fiica împ. Traian', 'red'),
(2026, 3, 23, 'Sf. Cuv. Mc. Nicon și cei 199 ucenici ai lui', 'black'),
(2026, 3, 24, 'Înainte-prăznuirea Bunei Vestiri; Sf. Ier. Artemon, ep. Seleuciei', 'black'),
(2026, 3, 25, '(†) Buna Vestire (Blagoveștenia)', 'red'),
(2026, 3, 26, 'Odovania Praznicului Bunei Vestiri; Soborul Sf. Arh. Gavriil; Sf. Mc. Montanus, pr. și soția sa, Maxima; Sf. 26 de Mc. din Goția/Dacia', 'black'),
(2026, 3, 27, 'Sf. Mc. Matrona din Tesalonic; Sf. Mc. Filit și Lidia, soția sa, cu cei 4 fii ai lor', 'black'),
(2026, 3, 28, 'Sf. Cuv. Ilarion cel Nou, eg. Pelechitului; Sf. Cuv. Ștefan, făcătorul de minuni', 'black'),
(2026, 3, 29, 'Sf. Sfințiți Mc. Marcu, ep. Aretuselor și Chiril diac.; Sf. Mc. Iona și Varahisie; Sf. Ier. Diadoh, ep. Foticeei;', 'red'),
(2026, 3, 30, 'Sf. Cuv. Ioan Scărarul; Sf. Cuv. Euvula, mama Sf. Pantelimon', 'black'),
(2026, 3, 31, 'Sf. Sfințit Mc. Ipatie, ep. Gangrei; Sf. Mc. Veniamin, diac.', 'black'),
-- April 2026
(2026, 4, 1, 'Sf. Cuv. Maria Egipteanca; Sf. Cuv. Macarie Mărt.; Sf. Mc. Gherontie; Sf. Varsanufie de la Optina', 'black'),
(2026, 4, 2, 'Sf. Cuv. Tit, făcătorul de minuni; Sf. Mc. Amfian și Edesie', 'black'),
(2026, 4, 3, 'Sf. Cuv. Nichita Mărt. și Ilirie', 'black'),
(2026, 4, 4, 'Sf. Cuv. Iosif Imnograful, Gheorghe din Maleon și Zosima', 'black'),
(2026, 4, 5, 'Sf. și Marea Luni; † Sf. Sfințit Mc. Irineu, ep. de Sirmium; Sf. Ier. Eutihie, patr. Constantinopolului; Sf. Cuv. Grigorie Sinaitul și Platonida', 'red'),
(2026, 4, 6, 'Sf. și Marea Luni; † Sf. Sfințit Mc. Irineu, ep. de Sirmium; Sf. Ier. Eutihie, patr. Constantinopolului; Sf. Cuv. Grigorie Sinaitul și Platonida', 'black'),
(2026, 4, 7, 'Sf. și Marea Marți; Sf. Mc. Caliopie; Sf. Ier. Gheorghe Mărt., ep. Mitilenei', 'black'),
(2026, 4, 8, 'Sf. și Marea Miercuri; Sf. Ap. Irodion, Agav, Ruf, Flegon, Asincrit și Ermis; Sf. Ier. Celestin, ep. Romei', 'black'),
(2026, 4, 9, 'Sf. și Marea Joi; Sf. Mc. Eupsihie din Cezareea Capadociei; Sf. Cuv. Vadim', 'black'),
(2026, 4, 10, 'Sf. și Marea Vineri - Scoaterea Sf. Aer; Sf. Mc. Terentie, Pompei, African, Maxim și Dima', 'black'),
(2026, 4, 11, 'Sf. și Marea Sâmbătă; †) Sf. Ier. Calinic de la Cernica, ep. Râmnicului; Sf. Sfințit Mc. Antipa, ep. Pergamului Asiei', 'black'),
(2026, 4, 12, '(†) A doua zi de Paști (Mărturia lui Ioan Botezătorul); †) Cinstirea Sf. Ic. a M. D. „Axion Estin" de la M. Protaton - Athos; Sf. Sfințit Mc. Artemon; Sf. Mc. Elefterie Persul. In aceasta zi se savarsesc si Slujbele Sfintilor romani din 11 si 12 aprilie: †) Sf. Ier. Calinic de la Cernica, ep. Râmnicului si mama sa Sf. Cuv. Filoteia de la Pasarea, si Sf. Mc. Sava de la Buzău', 'red'),
(2026, 4, 13, '(†) A doua zi de Paști (Mărturia lui Ioan Botezătorul); †) Cinstirea Sf. Ic. a M. D. „Axion Estin" de la M. Protaton - Athos; Sf. Sfințit Mc. Artemon; Sf. Mc. Elefterie Persul. In aceasta zi se savarsesc si Slujbele Sfintilor romani din 11 si 12 aprilie: †) Sf. Ier. Calinic de la Cernica, ep. Râmnicului si mama sa Sf. Cuv. Filoteia de la Pasarea, si Sf. Mc. Sava de la Buzău', 'red'),
(2026, 4, 14, '(†) A treia zi de Paști (Drumul spre Emaus); †) Sf. Ier. Pahomie de la Gledin, ep. Romanului; Sf. Ier. Martin Mărt., ep. Romei; Sf. Mc. Tomaida', 'red'),
(2026, 4, 15, 'Sf. Ap. Aristarh, Pud și Trofim; Sf. Mc. Crescent', 'black'),
(2026, 4, 16, 'Sf. Mc. fecioare Agapia, Irina și Hionia', 'black'),
(2026, 4, 17, '†) Izvorul Tămăduirii; †) Cinstirea Sf. Ic. a M. D. „Siriaca" de la M. Ghighiu; Sf. Sfințit Mc. Simeon, ep. Persiei', 'red'),
(2026, 4, 18, 'Sf. Cuv. Ioan, ucenicul Sf. Grigorie Decapolitul', 'black'),
(2026, 4, 19, 'Sf. Cuv. Ioan de la Lavra Veche; Sf. Sfințit Mc. Pafnutie', 'red'),
(2026, 4, 20, '† Sf. Ier. Teotim, ep. Tomisului; Sf. Cuv. Teodor Trihina', 'black'),
(2026, 4, 21, 'Sf. Sfințit Mc. Ianuarie, ep. de Benevent; Sf. Mc. Teodor din Perga; Sf. Mc. Alexandra, împ.', 'black'),
(2026, 4, 22, 'Sf. Ier. Teodor Sicheotul, ep. Anastasiopolei', 'black'),
(2026, 4, 23, '†) Sf. M. Mc. Gheorghe, Purtătorul de biruință; Sf. Mc. Valerie', 'red'),
(2026, 4, 24, '†) Sf. Ier. Mărt. Ilie Iorest, Sava Brancovici și Simion Ștefan, mitr. Transilvaniei; Sf. Ier. Iosif Mărt. din Maramureș; Sf. Mc. Pasicrat și Valentin; Sf. Cuv. Elisabeta', 'black'),
(2026, 4, 25, 'Sf. Ap. și Ev. Marcu; †) Sf. Cuv. Vasile de la Poiana Mărului', 'black'),
(2026, 4, 26, 'Sf. Sfințit Mc. Vasilevs, ep. Amasiei; Sf. Cuv. Glafira; † Soborul Sfintelor Femei Românce; † Sf. Mc. Chiril, Chindeu și Tasie din Axiopolis (Cernavodă)', 'red'),
(2026, 4, 27, 'Sf. Sfințit Mc. Simeon, ruda Domnului, ep. Ierusalimului', 'black'),
(2026, 4, 28, 'Sf. Ap. Iason și Sosipatru; † Sf. Mc. Maxim, Cvintilian și Dadas din Ozovia', 'black'),
(2026, 4, 29, 'Sf. 9 Mc. din Cizic; Sf. Cuv. Memnon, făcătorul de minuni', 'black'),
(2026, 4, 30, 'Sf. Ap. Iacob al lui Zevedeu, fratele Sf. Ap. și Ev. Ioan; Sf. Ier. Donat, ep. Evriei', 'black'),
-- May 2026
(2026, 5, 1, 'Sf. Prooroc Ieremia; Sf. Cuv. Mc. Eftimie, Ignatie și Acachie; Sf. Cuv. Isidora', 'black'),
(2026, 5, 2, 'Aducerea moaștelor Sf. Ier. Atanasie cel Mare în Constantinopol; †) Sf. Ier. Atanasie al III-lea (Patelarie), patr. Constantinopolului; Sf. Matrona din Moscova', 'black'),
(2026, 5, 3, '†) Sf. Cuv. Irodion de la Lainici; Sf. Mc. Timotei și soția sa, Mavra', 'red'),
(2026, 5, 4, '† Sf. Cuv. Mavra de pe Ceahlău; Sf. Mc. Pelaghia; Sf. Cuv. Monica, mama Fer. Augustin', 'black'),
(2026, 5, 5, '† Sf. Cuv. Matrona de la Hurezi; Sf. M. Mc. Irina; Sf. Cuv. Mc. Efrem cel Nou', 'black'),
(2026, 5, 6, 'Înjumătățirea praznicului Cincizecimii; Sf. și Dreptul Iov, mult răbdătorul; Sf. Mc. Varvar', 'black'),
(2026, 5, 7, 'Arătarea pe cer a semnului Sf. Cruci în Ierusalim; Sf. Mc. Acachie și Codrat', 'black'),
(2026, 5, 8, '†) Sf. Ap. și Ev. Ioan Teologul; Sf. Cuv. Arsenie cel Mare', 'black'),
(2026, 5, 9, 'Sf. Prooroc Isaia; Sf. Mc. Hristofor; Aducerea moaștelor Sf. Ier. Nicolae la Bari', 'black'),
(2026, 5, 10, 'Sf. Ap. Simon Zilotul; †) Sf. Cuv. Calistrat de la Timișeni și Vasiova', 'red'),
(2026, 5, 11, '†) Sf. Cuv. Dionisie Vatopedinul de la Colciu; Sf. Sfințit Mc. Mochie pr.;Sf. Ier. Metodie și Sf. Cuv. Chiril, luminătorii slavilor', 'black'),
(2026, 5, 12, '†) Sf. Mc. Ioan Valahul; Sf. Ier. Epifanie, arhiep. Ciprului și Gherman, patriarhul Constantinopolului', 'black'),
(2026, 5, 13, 'Odovania Înjumătățirii praznicului Cincizecimii; Sf. Mc. Glicheria; Sf. Cuv. Serghie Mărt.', 'black'),
(2026, 5, 14, 'Sf. Mc. Isidor din Hios; Sf. Sfințit Mc. Terapont, ep. Ciprului;', 'black'),
(2026, 5, 15, 'Sf. Cuv. Pahomie cel Mare; †) Sf. Ier. Iacob Putneanul, mitr. Moldovei', 'black'),
(2026, 5, 16, 'Sf. Cuv. Teodor cel Sfințit; †) Sf. Cuv. Sila, Paisie și Natan de la Sihăstria Putnei', 'black'),
(2026, 5, 17, 'Sf. Ap. Andronic și soția sa, Iunia; Sf. Cuv. Nectarie și Teofan', 'red'),
(2026, 5, 18, 'Sf. Mc. Petru, Dionisie și Paulin', 'black'),
(2026, 5, 19, 'Sf. Mc. Patrichie, ep. Prusei', 'black'),
(2026, 5, 20, 'Odovania praznicului Învierii Domnului; Sf. Mc. Talaleu; Sf. Cuv. Talasie; Sf. Lidia din Filipi', 'black'),
(2026, 5, 21, '(†) Înălțarea Domnului (Ispasul); Ziua Eroilor; †) Sf. Împ., întocmai cu ap., Constantin și mama sa, Elena', 'red'),
(2026, 5, 22, 'Sf. Mc. Vasilisc și Marcel; Sf. Părinți de la Sinodul al II-lea Ecumenic', 'black'),
(2026, 5, 23, 'Sf. Ier. Mihail Mărt., ep. Sinadei; Sf. Mironosiță Maria lui Cleopa', 'black'),
(2026, 5, 24, '† Sf. Mărt. Blandina de la Iași; Sf. Cuv. Simeon cel din Muntele Minunat', 'red'),
(2026, 5, 25, '† A treia aflare a capului Sf. Ioan, Înaintemergătorul și Botezătorul Domnului', 'black'),
(2026, 5, 26, 'Sf. Ap. Carp și Alfeu; Sf. Mc. Averchie și Elena', 'black'),
(2026, 5, 27, 'Sf. Mc. Iuliu Veteranul; Sf. Sfințiți Mc. Eladie și Terapont, ep. Sardei; Sf. Mărt. Ioan Rusul', 'black'),
(2026, 5, 28, 'Sf. Ier. Eutihiei, ep. Melitinei și Nichita, ep. Calcedonului', 'black'),
(2026, 5, 29, 'Odovania praznicului Înălțării Domnului; Sf. Mc. Teodosia, fecioara; Sf. Sfințit Mc. Olivian', 'black'),
(2026, 5, 30, 'Sf. Cuv. Isaachie Mărt. și Varlaam', 'black'),
(2026, 5, 31, 'Rusalii - Pogorârea Duhului Sfânt', 'red'),
-- June 2026
(2026, 6, 1, '†) Sf. M. Mc. Ioan cel Nou de la Suceava; Sf. Ier. Nichifor, patr. Constantinopolului', 'red'),
(2026, 6, 2, '†) Sf. M. Mc. Ioan cel Nou de la Suceava; Sf. Ier. Nichifor, patr. Constantinopolului', 'black'),
(2026, 6, 3, 'Sf. Mc. Luchilian, Ipatie și Paula fecioara', 'black'),
(2026, 6, 4, '†) Sf. Mc. Zotic, Atal, Camasie și Filip de la Niculițel; Sf. Ier. Mitrofan, patr. Constantinopolului; Sf. Mironosițe Maria și Marta, surorile Dreptului Lazăr', 'black'),
(2026, 6, 5, '† Sf. Cuv. Elisabeta de la Pasărea; Sf. Sfințit Mc. Dorotei, ep. Tirului; Sf. Mc. Apolon și Leonid', 'black'),
(2026, 6, 6, 'Odovania praznicului Pogorârii Sf. Duh; Sf. Cuv. Ilarion cel Nou, eg. M. Dalmaților; Sf. Cuv. Visarion', 'black'),
(2026, 6, 7, 'Sf. Sfințit Mc. Teodot, ep. Ancirei; Sf. Mc. Zenaida', 'red'),
(2026, 6, 8, '† Sf. Mc. Nicandru și Marcian; Aducerea moaștelor Sf. M. Mc. Teodor Stratilat', 'black'),
(2026, 6, 9, 'Sf. Ier. Chiril, arhiep. Alexandriei', 'black'),
(2026, 6, 10, 'Sf. Mc. Alexandru și Antonina; Sf. Sfințit Mc. Timotei, ep. Prusiei', 'black'),
(2026, 6, 11, 'Sf. Ap. Bartolomeu și Barnaba; Sf. Ier. Luca, arhiep. Crimeei', 'black'),
(2026, 6, 12, 'Sf. Cuv. Onufrie cel Mare și Petru Atonitul', 'black'),
(2026, 6, 13, 'Sf. Mc. Achilina; Sf. Ier. Trifilie, ep. Lefcosiei din Cipru', 'black'),
(2026, 6, 14, 'Sf. Prooroc Elisei; Sf. Ier. Metodie Mărturisitorul, patriarhul Constantinopolului', 'red'),
(2026, 6, 15, 'Sf. Prooroc Amos; † Sf. Mc. Isihie; Fer. Augustin și Ieronim', 'black'),
(2026, 6, 16, '†) Sf. Ier. Martir Neofit Cretanul, mitropolitul Țării Româneti; Sf. Ier. Tihon, ep. Amatundei', 'black'),
(2026, 6, 17, 'Sf. Mc. Manuil, Savel, Ismail, Inochentie și Felix', 'black'),
(2026, 6, 18, 'Sf. Mc. Leontie, Ipatie și Teodul; Sf. Cuv. Erasm', 'black'),
(2026, 6, 19, 'Sf. Ap. Iuda, ruda Domnului; Sf. Cuv. Paisie cel Mare', 'black'),
(2026, 6, 20, 'Sf. Sfințit Mc. Metodie, ep. Patarelor; Sf. Ier. Calist, patr. Constantinopolului; Sf. Nicolae Cabasila', 'black'),
(2026, 6, 21, 'Sf. Mc. Iulian din Tars și Afrodisie', 'red'),
(2026, 6, 22, '†) Sf. Ier. Grigorie Dascălul, mitr. Țării Românești; Sf. Sfințit Mc. Eusebiu, ep. Samosatei', 'black'),
(2026, 6, 23, 'Sf. Mc. Agripina; Sf. Sfințit Mc. Aristocleu, pr.', 'black'),
(2026, 6, 24, '(†) Nașterea Sf. Proroc Ioan Botezătorul (Sânzienele); † Aducerea moaștelor Sf. M. Mc. Ioan cel Nou de la Suceava; † Sf. Ier. Niceta de Remesiana;', 'red'),
(2026, 6, 25, 'Sf. M. Mc. Fevronia; Sf. Mc. Orentie și frații săi; Sf. Mc. Livia', 'black'),
(2026, 6, 26, 'Sf. Cuv. David din Tesalonic; Sf. Ier. Ioan, ep. Goției', 'black'),
(2026, 6, 27, 'Sf. Cuv. Samson, primitorul de străini; Sf. Mironosiță Ioana', 'black'),
(2026, 6, 28, 'Aducerea moaștelor Sf. Mc. Doctori fără de arginți Chir și Ioan; Sf. Mc. Papias', 'red'),
(2026, 6, 29, '(†) Sf. Ap. Petru și Pavel', 'red'),
(2026, 6, 30, '† Soborul Sf. 12 Ap.; †) Sf. Ier. Ghelasie de la Râmeț', 'black'),
-- July 2026
(2026, 7, 1, '†) Sf. Ier. Leontie de la Rădăuți; Sf. Mc. Doctori fără de arginți, Cosma și Damian, cei din Roma', 'black'),
(2026, 7, 2, 'Așezarea veșmântului Născătoarei de Dumnezeu în biserica Vlaherne; †) Sf. Voievod Ștefan cel Mare; Sf. Ier. Iuvenalie, patr. Ierusalimului; Sf. Ier. Ioan Maximovici', 'black'),
(2026, 7, 3, 'Sf. Mc. Iachint; Sf. Ier. Anatolie, patr. Constantinopolului', 'black'),
(2026, 7, 4, '† Sf. Olimpia de la Farcașa. ; Sf. Ier. Andrei, arhiep. Cretei; Sf. Cuv. Marta', 'black'),
(2026, 7, 5, '† Sf. Cuv. Atanasie Atonitul; Sf. Cuv. Lampadie', 'red'),
(2026, 7, 6, '†) Sf. Cuv. Dometie cel Milostiv de la Râmeț și mama sa, Sf. Cuv. Filotimia; Sf. Cuv. Sisoe cel Mare; Sf. Mc. Lucia din Roma; Sf. Mc. Marius, soția sa, Marta, și fiii lor, Audifaciu și Avacum', 'black'),
(2026, 7, 7, '†) Sf. M. Mc. Chiriachi; Sf. Cuv. Toma din Maleon; Sf. Mc. Evanghel', 'black'),
(2026, 7, 8, 'Sf. M. Mc. Procopie; Sf. Mc. Teofil și Epictet', 'black'),
(2026, 7, 9, '† Sf. Cuv. Codrat și Patapie de la Karakalu; Sf. Sfințit Mc. Pangratie, ep. Taormeniului; Sf. Mc. Chiriachi', 'black'),
(2026, 7, 10, '† Sf. Cuv. Gheorghe de la Pisania și Gavriil, ierod. din Valahia Mare; Sf. Sfințit Mc. Acvila; Sf. Mc. Luca; Sf. 45 de Mc. din Nicopolea Armeniei; Sf. Cuv. Antonie Pecerscul', 'black'),
(2026, 7, 11, 'Sf. M. Mc. Eufimia; Sf. Olga, întocmai cu Ap. și luminătoarea Rusiei', 'black'),
(2026, 7, 12, '†) Sf. Cuv. Paisie Aghioritul; Sf. Mc. Prociu și Ilarie; Sf. Cuv. Mihail Maleinos', 'red'),
(2026, 7, 13, '† Sf. Arh. Gavriil (Gavrilă); Soborul Sf. Arh. Gavriil; Sf. Cuv. Ștefan Savaitul', 'black'),
(2026, 7, 14, 'Sf. Ap. Acvila și soția sa, Priscila; Sf. Mc. Iust; Sf. Cuv. Iosif, ep. Tesalonicului', 'black'),
(2026, 7, 15, 'Sf. Mc. Chiric și mama sa, Iulita; †) Sf. Voievod Vladimir, luminătorul Rusiei', 'black'),
(2026, 7, 16, 'Sf. Sfințit Mc. Atinoghen, ep. Sevastiei, și cei 10 ucenici ai săi; Sf. Mc. Favrenie și Iulia', 'black'),
(2026, 7, 17, 'Sf. M. Mc. Marina; Sf. Ier. Eufrasie, ep. Ionopolei', 'black'),
(2026, 7, 18, '†) Sf. Mc. Emilian de la Durostorum (Ostrov); Sf. Cuv. Pamvo', 'black'),
(2026, 7, 19, 'Sf. Cuv. Macrina, sora Sf. Vasile cel Mare; Sf. Cuv. Die; Aflarea moaștelor Sf. Cuv. Serafim de Sarov', 'red'),
(2026, 7, 20, '†) Sf. Slăvitul Prooroc Ilie Tesviteanul', 'red'),
(2026, 7, 21, 'Sf. Cuv. Simeon și Ioan Pustnicul; Sf. Prooroc Iezechiel; †) Sf. Cuv. Rafail și Partenie, de la Agapia Veche', 'black'),
(2026, 7, 22, '†) Sf. Pr. Mărt. Ilie Lăcătușu; Sf. Mironosiță, întocmai cu Ap., Maria Magdalena; Sf. Cuv. Mc. Marcela', 'black'),
(2026, 7, 23, 'Aducerea Moaștelor Sf. Sfințit Mc. Foca; Sf. Mc. Apolinarie, Vitalie și Valeria', 'black'),
(2026, 7, 24, 'Sf. M. Mc. Hristina; Sf. Mc. Ermoghen', 'black'),
(2026, 7, 25, 'Adormirea Sf. Ana, mama Preasfintei Născătoare de Dumnezeu; Sf. Părinți de la Sinodul al V-lea Ecumenic; Sf. Cuv. Eupraxia și Olimpiada', 'black'),
(2026, 7, 26, 'Sf. Sfințit Mc. Ermolae; Sf. Mc. Cuv. Paraschevi din Roma; †) Sf. Cuv. Ioanichie cel Nou de la Muscel (Argeș)', 'red'),
(2026, 7, 27, '† Sf. M. Mc. și Tămăduitor Pantelimon', 'black'),
(2026, 7, 28, 'Sf. Ap. și Diac. Prohor, Nicanor, Timon și Parmena; Sf. Cuv. Pavel de la Xiropotamu', 'black'),
(2026, 7, 29, 'Sf. Mc. Calinic, Veniamin și Mamant; Sf. Mc. Teodota cu fiii săi', 'black'),
(2026, 7, 30, 'Sf. Ap. Sila, Silvan, Crescent, Epenet și Andronic; Sf. Mc. Valentin, ep. Umbriei', 'black'),
(2026, 7, 31, 'Înainte-prăznuirea scoaterii Sf. Cruci; Sf. și Dreptul Evdochim; Sf. și Dreptul Iosif din Arimateea', 'black'),
-- August 2026
(2026, 8, 1, 'Scoaterea Sf. Cruci; Sf. 7 frați Mc. Macabei', 'black'),
(2026, 8, 2, 'Aducerea moaștelor Sf. Întâi Mc. și Arhid. Ștefan; Dreptul Gamaliel; Binecredinciosul Împ. Iustinian cel Mare', 'red'),
(2026, 8, 3, '†) Sf. Cuv. Mărt. Iraclie din Basarabia; Sf. Cuv. Isaachie, Dalmat și Faust; Sf. Mironosiță Salomeea; Sf. Cuv. Teodora din Tesalonic', 'black'),
(2026, 8, 4, 'Sf. 7 tineri din Efes; Sf. Mc. Tatuil', 'black'),
(2026, 8, 5, 'Înainte-prăznuirea Schimbării la Față a Domnului; †) Sf. Cuv. Ioan Iacob de la Neamț; Sf. Mc. Evsignie; Sf. Nona, mama Sf. Ier. Grigorie Teologul; Sf. Ier. Fabian, ep. Romei', 'black'),
(2026, 8, 6, '(†) Schimbarea la Față a Domnului (Pobrejenia)', 'red'),
(2026, 8, 7, '†) Sf. Cuv. Teodora de la Sihla; †) Sf. Cuv. Pafnutie - Pârvu Zugravul; Sf. Cuv. Mc. Dometie Persul; Sf. Sfințit Mc. Narcis, arhep. Ierusalimului; Sf. Cuv. Nicanor', 'black'),
(2026, 8, 8, '†) Sf. Pr. Mc. Alexandru din Basarabia; Sf. Ier. Emilian Mărt., ep. Cizicului și Miron, ep. Cretei', 'black'),
(2026, 8, 9, 'Sf. Ap. Matia; Sf. 10 Mc. Mărt. pentru icoana lui Hristos', 'red'),
(2026, 8, 10, 'Sf. Mc. Laurențiu, arhid.; Sf. Sfințit Mc. Xist, ep. Romei; Sf. Mc. Ipolit', 'black'),
(2026, 8, 11, '†) Sf. Ier. Nifon, patr. Constantinopolului; Sf. M. Mc. Evplu, arhid.', 'black'),
(2026, 8, 12, 'Sf. Mc. Fotie și Anichit', 'black'),
(2026, 8, 13, 'Odovania praznicului Schimbării la Față a Domnului; Mutarea moaștelor Sf. Cuv. Maxim Mărt.; Sf. Cuv. Dorotei și Dositei', 'black'),
(2026, 8, 14, 'Înainte-prăznuirea Adormirii Maicii Domnului; Sf. Prooroc Miheia', 'black'),
(2026, 8, 15, '(†) Adormirea Maicii Domnului', 'red'),
(2026, 8, 16, 'Aducerea Sf. Mahrame a Domnului din Edesa la Constantinopol; †) Sf. Martiri Brâncoveni: Constantin Voievod cu cei patru fii ai săi: Constantin, Ștefan, Radu și Matei, și sfetnicul Ianache; †) Sf. Cuv. Iosif de la Văratec; Sf. Mc. Diomid', 'red'),
(2026, 8, 17, '†) Sf. Gheorghe Pelerinul; † Sf. Cuv. Nazaria, Olimpiada, Elisabeta (Safta) Brâncoveanu, de la Văratec ; Sf. Mc. Miron pr., Straton și Ciprian', 'black'),
(2026, 8, 18, 'Sf. Mc. Flor și Lavru', 'black'),
(2026, 8, 19, 'Sf. Mc. Andrei Stratilat, Timotei, Agapie și Tecla', 'black'),
(2026, 8, 20, 'Sf. Prooroc Samuel; Sf. Mc. Sever, Eliodor și Teoharie', 'black'),
(2026, 8, 21, 'Sf. Ap. Tadeu; Sf. Mc. Vasa, cu fiii ei; † Sf. Mc. Donat diac., Romul pr., Silvan diac. și Venust', 'black'),
(2026, 8, 22, 'Sf. Mc. Agatonic și cei îmtruna cu ei', 'black'),
(2026, 8, 23, 'Odovania praznicului Adormirii Maicii Domnului; † Sf. Mc. Lup; Sf. Sfințit Mc. Irineu, ep. de Lugdunum (Lyon)', 'red'),
(2026, 8, 24, 'Sf. Sfințit Mc. Eutihie; Sf. Mc. Tation', 'black'),
(2026, 8, 25, 'Aducerea moaștelor Sf. Ap. Bartolomeu; Sf. Ap. Tit', 'black'),
(2026, 8, 26, 'Sf. Mc. Adrian și Natalia, soția sa', 'black'),
(2026, 8, 27, 'Sf. Cuv. Pimen cel Mare; Sf. Mc. Fanurie; Sf. Ier. Osie, ep. Cordobei', 'black'),
(2026, 8, 28, 'Sf. Cuv. Moise Etiopianul; Dreptul Iezechia', 'black'),
(2026, 8, 29, '(†) Tăierea Capului Sf. Prooroc Ioan Botezătorul; Fapte XIII, 25-33', 'red'),
(2026, 8, 30, '†) Sf. Ier. Varlaam, mitr. Moldovei și Ioan de la Râșca și Secu, ep. Romanului; Sf. Ier. Ioan, Pavel cel Nou și Alexandru, patr. Constantinopolului', 'red'),
(2026, 8, 31, 'Așezarea în raclă a cinstitului brâu al Maicii Domnului; †) Sf. Cuv. Macarie Protopsaltul', 'black'),
-- September 2026
(2026, 9, 1, '† Începutul anului bisericesc; † Sf. Cuv. Dionisie Exiguul (cel Smerit); Sf. Cuv. Simeon Stâlpnicul; Sf. 40 de Mucenițe din Adrianopol; Dreptul Iosua', 'black'),
(2026, 9, 2, 'Sf. Mc. Mamant; Sf. Ier. Ioan Postitorul, patr. Constantinopolului', 'black'),
(2026, 9, 3, 'Sf. Sfințit Mc. Antim, ep. Nicomidiei; Sf. Cuv. Teoctist din Palestina; †) Sf. Cuv. Neofit și Meletie de la M-rea. Stânișoara', 'black'),
(2026, 9, 4, 'Sf. Sfințit Mc. Vavila, ep. Antiohiei; Sf. Prooroc Moise; Sf. Mc. Petroniu', 'black'),
(2026, 9, 5, 'Sf. Prooroc Zaharia și Dreapta Elisabeta, părinții Sf. Ioan Botezătorul', 'black'),
(2026, 9, 6, 'Pomenirea minunii Sf. Arh. Mihail în Colose; Sf. Mc. Eudoxie;', 'red'),
(2026, 9, 7, 'Înainte-prăznuirea Nașterii Maicii Domnului; Sf. Mc. Sozont; Sf. Cuv. Casiana Imnografa; †) Sf. Cuv. Simeon și Amfilohie de la Pângărați', 'black'),
(2026, 9, 8, '(†) Nașterea Maicii Domnului', 'red'),
(2026, 9, 9, 'Sf. și Drepții dumnezeiești Părinți Ioachim și Ana; †) Sf. Cuv. Chiriac de la Tazlău; †) Sf. Cuv. Onufrie de la Vorona; Sf. Părinți de la Sinodul al III-lea Ecumenic; Sf. Mc. Severian', 'black'),
(2026, 9, 10, 'Sf. Mc. Minodora, Mitrodora și Nimfodora; Sf. Împ. Pulheria', 'black'),
(2026, 9, 11, 'Sf. Cuv. Teodora din Alexandria; Sf. Cuv. Eufrosin Bucătarul', 'black'),
(2026, 9, 12, 'Odovania Praznicului Nașterii Maicii Domnului; Sf. Mc. Avtonom, Macedonie și Teodul', 'black'),
(2026, 9, 13, 'Înainte-prăznuirea Înălțării Sf. Cruci; † Târnosirea Bisericii Învierii din Ierusalim; Sf. Sfințiți Mc. Corneliu Sutașul și Ciprian, ep. Cartaginei; †) Sf. Cuv. Ioan de la Prislop; † Sf. Mc. din Dobrogea: Macrobie, Gordian, Ilie, Zotic, Lucian și Valerian', 'red'),
(2026, 9, 14, '(†) Înălțarea Sfintei Cruci; Sf. Nou Mc. Macarie, ucenicul patr. Nifon', 'red'),
(2026, 9, 15, '†) Sf. Ier. Iosif cel Nou de la Partoș, mitr. Banatului; † Sf. M. Mc. Nichita; † Sf. Ier. Visarion, arhiep. Larisei', 'black'),
(2026, 9, 16, '†) Sf. Cuv. Mărt. Sofian de la Antim; Sf. M. Mc. Eufimia; Sf. Mc. Meletina și Ludmila', 'black'),
(2026, 9, 17, '†) Sf. Ier. Dionisie, ep. Cetății Albe - Ismail; Sf. Mc. Sofia și fiicele sale: Pistis, Elpis și Agapi', 'black'),
(2026, 9, 18, '†) Sf. Pr. Mc. Ilarion Felea; Sf. Ier. Eumenie, ep. Gortinei; Sf. Mc. Ariadna', 'black'),
(2026, 9, 19, 'Sf. Mc. Trofim, Savatie și Dorimedont', 'black'),
(2026, 9, 20, 'Sf. M. Mc. Eustatie și soția sa, Teopista, cu cei doi fii ai lor: Agapie și Teopist', 'red'),
(2026, 9, 21, 'Odovania Praznicului Înălțării Sfintei Cruci; Sf. Ap. Codrat; Sf. Prooroc Iona', 'black'),
(2026, 9, 22, '†) Sf. Ier. Mc. Teodosie de la M. Brazi, mitr. Moldovei; Sf. Sfințit Mc. Foca, ep. de Sinope', 'black'),
(2026, 9, 23, 'Zămislirea Sf. Prooroc Ioan Botezătorul; Sf. Cuv. Xantipa și Polixenia', 'black'),
(2026, 9, 24, 'Sf. întâia Mc., întocmai cu ap., Tecla; Sf. Cuv. Siluan Athonitul', 'black'),
(2026, 9, 25, 'Sf. Cuv. Eufrosina; Sf. Cuv. Pafnutie Egipteanul; Sf. Cuv. Serghie de la Radonej', 'black'),
(2026, 9, 26, '†) Mutarea Sf. Ap. și Ev. Ioan; †) Sf. Voievod Neagoe Basarab; Sf. Cuv. Platonide de la Argeș (fosta Despina Milița, soția voievodului); Dreptul Ghedeon', 'black'),
(2026, 9, 27, '†) Sf. Ier. Martir Antim Ivireanul, mitr. Țării Românești; Sf. Mc. Calistrat și Epiharia', 'red'),
(2026, 9, 28, '† Sf. Cuv. Hariton Mărt.; Sf. Prooroc Baruh; Sf. Neofit Zăvorâtul din Cipru', 'black'),
(2026, 9, 29, 'Sf. Cuv. Chiriac Sihastrul; Sf. Mc. Petronia', 'black'),
(2026, 9, 30, 'Sf. Ier. Grigorie Luminătorul, arhiep. Armeniei; Sf. Mc. Ripsimia și Gaiani', 'black'),
-- October 2026
(2026, 10, 1, '(†) Acoperământul Maicii Domnului; Sf. Ap. Anania; Sf. Cuv. Roman Melodul; †) Sf. Cuv. Chiriac și Iosif de la Bisericani', 'red'),
(2026, 10, 2, 'Sf. Sfințit Mc. Ciprian; Sf. Mc. Iustina fecioara', 'black'),
(2026, 10, 3, 'Sf. Sfințit Mc. Dionisie Areopagitul; Sf. Mc. Teoctist', 'black'),
(2026, 10, 4, '†) Sf. Pr. Mărt. Dumitru Stăniloae; Sf. Sfințit Mc. Ierotei, ep. Atenei', 'red'),
(2026, 10, 5, 'Sf. Mc. Haritina; †) Sf. Cuv. Misail și Daniil de la Mănăstirea Turnu', 'black'),
(2026, 10, 6, 'Sf. Ap. Toma; Sf. Mc. Erotiida', 'black'),
(2026, 10, 7, '† Sf. M. Mc. Serghie și Vah; Sf. Mc. Iulian pr., Chesarie diac. și Polihronie', 'black'),
(2026, 10, 8, 'Sf. Cuv. Pelaghia și Taisia', 'black'),
(2026, 10, 9, 'Sf. Ap. Iacov al lui Alfeu; Sf. Cuv. Atanasia, Andronic și Anastasia', 'black'),
(2026, 10, 10, 'Sf. Mc. Evlampie și sora sa, Evlampia; Sf. Cuv. Vasian și Teofil Mărt.', 'black'),
(2026, 10, 11, 'Sf. Ap. Filip, unul din cei 7 diac.; Sf. Ier. Teofan Mărt., ep. Niceei', 'red'),
(2026, 10, 12, 'Sf. Mc. Prov, Tarah și Andronic; Sf. Ier. Cosma, ep. Maiumei', 'black'),
(2026, 10, 13, '† Aducerea moaștelor Sf. Ap. Andrei la Iași; Sf. Mc. Carp, Papil, Agatodor, Agatonica și Florentie', 'black'),
(2026, 10, 14, '†) Sf. Cuv. Parascheva de la Iași; Sf. Mc. Nazarie, Ghervasie, Protasie și Chelsie', 'red'),
(2026, 10, 15, '† Sf. Magdalena de la Mălainița; Sf. Mc. Luchian, pr. din Antiohia', 'black'),
(2026, 10, 16, 'Sf. Mc. Longhin Sutașul', 'black'),
(2026, 10, 17, 'Sf. Prooroc Oseea; Sf. Cuv. Mc. Andrei Criteanul', 'black'),
(2026, 10, 18, 'Sf. Ap. și Ev. Luca; Sf. Mc. Marin cel Bătrân', 'red'),
(2026, 10, 19, 'Sf. Prooroc Ioil; Sf. Mc. Uar; Sf. Cleopatra; Sf. Cuv. Ioan de la Rila;', 'black'),
(2026, 10, 20, 'Sf. M. Mc. Artemie; Sf. Gherasim din Chefalonia', 'black'),
(2026, 10, 21, '†) Sf. Cuv. Mărt. Visarion și Sofronie; Sf. Mc. Oprea; Sf. Pr. Mărt. Ioan din Galeș și Moise Măcinic din Sibiel; Sf. Cuv. Ilarion cel Mare', 'black'),
(2026, 10, 22, 'Sf. Ier. Averchie, ep. Ierapolei; Sf. 7 tineri din Efes;', 'black'),
(2026, 10, 23, 'Sf. Ap. Iacob, ruda Domnului, întâiul ep. al Ierusalimului; †) Sf. Pr. Mc. Constantin Sârbu; Sf. Cuv. Macarie Romanul', 'black'),
(2026, 10, 24, 'Sf. M. Mc. Areta; Sf. Mc. Marcu, Sotirih și Valentin', 'black'),
(2026, 10, 25, 'Sf. Mc. Marcian și Martirie; Sf. Tavita', 'red'),
(2026, 10, 26, '†) Sf. M. Mc. Dimitrie, Izvorâtorul de mir', 'red'),
(2026, 10, 27, '†) Sf. Cuv. Dimitrie cel Nou, Ocrotitorul Bucureștilor, ale cărui moaște se află în Catedrala Patriarhală; Sf. Mc. Nestor', 'red'),
(2026, 10, 28, '† Sf. Ier. Iachint, mitr. Țării Românești; †) Sf. Cuv. Teofana Basarab; Sf. Mc. Terentie, soția sa Neonila și cei 7 fii ai lor: Nita, Sarvil, Ierax, Teodul, Fota, Vilie si Evnichi; Sf. Ier. Firmilian, ep. Cezareei Capadociei;', 'black'),
(2026, 10, 29, 'Sf. M. Mc. Anastasia Romana; Sf. Cuv. Avramie și Maria, nepoata sa', 'black'),
(2026, 10, 30, 'Sf. Sfințit Mc. Zenovie, ep. Ciliciei și sora sa, Zenovia; Sf. Ap. Cleopa', 'black'),
(2026, 10, 31, 'Sf. Ap. Apelie, Stahie, Amplie, Urban, Aristobul și Narcis; Sf. Mc. Epimah', 'black'),
-- November 2026
(2026, 11, 1, 'Sf. doctori fără de arginți Cosma și Damian, cei din Asia', 'red'),
(2026, 11, 2, 'Sf. Mc. Achindin, Pigasie, Aftonie, Elpifidor și Anempodist', 'black'),
(2026, 11, 3, 'Sf. Mc. Achepsima ep., Iosif pr. și Aitala diac.; Așezarea moaștelor Sf. M. Mc. Gheorghe în Lida', 'black'),
(2026, 11, 4, 'Sf. Cuv. Ioanichie cel Mare; Sf. Mc. Nicandru și Ermeu; Sf. Cuv.Gheorghe Mărt. din Drama', 'black'),
(2026, 11, 5, 'Sf. Mc. Galaction și Epistimia', 'black'),
(2026, 11, 6, 'Sf. Pavel Mărt., patr. Constantinopolului; Sf. Cuv. Luca din Sicilia', 'black'),
(2026, 11, 7, 'Sf. 33 de Mc. din Melitina; Sf. Cuv. Lazăr din Muntele Galisiei', 'black'),
(2026, 11, 8, '†) Soborul Sf. Arh. Mihail și Gavriil și al tuturor cereștilor puteri', 'red'),
(2026, 11, 9, '†) Sf. Ier. Nectarie Taumaturgul de la Eghina; Sf. Mc. Claudiu, Castor, Sempronian și Nicostrat; Sf. Mc. Onisifor și Porfirie; Sf. Cuv. Matrona', 'black'),
(2026, 11, 10, 'Sf. Ap. Olimp, Rodion, Sosipatru, Erast, Terțiu și Cvart; †) Sf. Cuv. Mc. Visarion de la Lainici; Sf. Mc. Orest', 'black'),
(2026, 11, 11, '† Sf. M. Mc. Mina; Sf. Mc. Victor, Vichentie și Ștefanida; Sf. Cuv. Teodor Studitul', 'black'),
(2026, 11, 12, 'Sf. Ier. Ioan cel Milostiv, patr. Alexandriei; †) Sf. Martiri și Mărt. Năsăudeni: Atanasie Todoran din Bichigiu, Vasile din Mocod, Grigorie din Zagra și Vasile din Telciu; Sf. Cuv. Nil Pustnicul', 'black'),
(2026, 11, 13, '†) Sf. Ier. Ioan Gură de Aur, arhiep. Constantinopolului și mama sa, Sf. Antuza', 'black'),
(2026, 11, 14, '†) Sf. Ap. Filip unul dintre cei 12 Apostoli; Sf. Ier. Grigorie Palama, arhiep. Tesalonicului', 'black'),
(2026, 11, 15, '†) Sf. Cuv. Paisie de la Neamț; Sf. Mc. și Mărt. Gurie, Samona și Aviv, diac.', 'red'),
(2026, 11, 16, 'Sf. Ap. și Ev. Matei', 'black'),
(2026, 11, 17, 'Sf. Ier. Grigorie Taumaturgul, ep. Neocezareei Pontului și Ghenadiei, patr. Constantinopolului; Sf. Cuv. Lazăr Zugravul', 'black'),
(2026, 11, 18, 'Sf. Mc. Platon, Roman și Zaheu', 'black'),
(2026, 11, 19, 'Sf. Prooroc Avdie; Sf. Mc. Varlaam', 'black'),
(2026, 11, 20, 'Înainte-prăznuirea Intrării în Biserică a Maicii Domnului; †) Sf. Cuv. Grigorie Decapolitul; † Sf. Mc. Dasie; Sf. Ier. Proclu, arhiep. Constantinopolului;', 'black'),
(2026, 11, 21, '(†) Intrarea în Biserică a Maicii Domnului (Vovidenia)', 'red'),
(2026, 11, 22, 'Sf. Ap. Filimon, Arhip, Onisim și Apfia; Sf. Mc. Cecilia', 'red'),
(2026, 11, 23, '† Sf. Cuv. Antonie de la Iezerul Vâlcii; Sf. Ier. Amfilohie, ep. Iconiei și Grigorie, ep. Acragandelor', 'black'),
(2026, 11, 24, 'Sf. Sfințiți Mc. Clement, ep. Romei și Petru, ep. Alexandriei', 'black'),
(2026, 11, 25, 'Odovania Praznicului Intrării în Biserică a Maicii Domnului; † Sf. M. Mc. Ecaterina; Sf. M. Mc. Mercurie', 'black'),
(2026, 11, 26, 'Sf. Cuv. Alipie Stâlpnicul, Nicon și Stelian Paflagonul', 'black'),
(2026, 11, 27, 'Sf. M. Mc. Iacob Persul; Sf. Cuv. Natanail și Pinufrie', 'black'),
(2026, 11, 28, '†) Sf. Cuv. Mărt. Arsenie de la Proslop; Sf. Cuv. Mc. Ștefan cel Nou; Sf. Mc. Irinarh', 'black'),
(2026, 11, 29, 'Sf. Mc. Paramon și Filumen; Sf. Cuv. Pitirun', 'red'),
(2026, 11, 30, '†) Sf. Ap. Andrei, cel Întâi Chemat, Ocrotitorul României; †) Sf. Ier. Andrei Șaguna, mitr. Transilvaniei; Sf. Ier. Frumentie, ep. Etiopiei', 'red'),
-- December 2026
(2026, 12, 1, '† Sf. Anastasia, mama Sfântului Ier. Andrei Șaguna; Sf. Prooroc Naum; Sf. Cuv. Filaret cel Milostiv', 'black'),
(2026, 12, 2, '†) Sf. Cuv. Paisie și Cleopa de la Sihăstria; Sf. Prooroc Avacum; Sf. Mc. Miropi; Sf. Porfirie Cavsocalivitul; Sf. Ier. Solomon, arhiep. Efesului', 'black'),
(2026, 12, 3, '†) Sf. Cuv. Gheorghe de la Cernica și Căldărușani; Sf. Prooroc Sofonie', 'black'),
(2026, 12, 4, '† Sf. M. Mc. Varvara; Sf. Cuv. Ioan Damaschin', 'black'),
(2026, 12, 5, '†) Sf. Cuv. Sava cel Sfințit; Sf. Mc. Anastasie', 'black'),
(2026, 12, 6, '†) Sf. Ier. Nicolae, arhiep. Mirelor Lichiei, făcătorul de minuni', 'red'),
(2026, 12, 7, '†) Sf. Mc. Filofteia de la Curtea de Argeș; Sf. Ier. Ambrozie, ep. Mediolanului (Milano)', 'black'),
(2026, 12, 8, 'Sf. Cuv. Patapie; Sf. Ap. Cezar, Tihic și Onisifor', 'black'),
(2026, 12, 9, 'Zămislirea Sfintei Fecioare Maria de către Sf. Ana; Sf. Proorociță Ana, mama Proorocului Samuel', 'black'),
(2026, 12, 10, 'Sf. Mc. Mina, Ermoghen și Evgraf', 'black'),
(2026, 12, 11, 'Sf. Cuv. Daniil Stâlpnicul și Luca cel Nou', 'black'),
(2026, 12, 12, '†) Sf. Ier. Spiridon, ep. Trimitundei, făcătorul de minuni', 'black'),
(2026, 12, 13, '†) Sf. Ier. Dosoftei, mitr. Moldovei; † Sf. M. Mc. Eustratie, Auxentie, Evghenie, Mardarie și Orest; Sf. Mc. Lucia, fecioara din Siracuza', 'red'),
(2026, 12, 14, 'Sf. Mc. Tirs, Calinic, Filimon și Apolonie', 'black'),
(2026, 12, 15, 'Sf. Sfințit Mc. Elefterie, ep. Iliriei; Sf. Mc. Antia și Suzana; Sf. Cuv. Pavel din Latro', 'black'),
(2026, 12, 16, 'Sf. Prooroc Agheu; Sf. Teofana, împ.', 'black'),
(2026, 12, 17, 'Sf. Prooroc Daniel și Sf. trei tineri: Anania, Azaria și Misail', 'black'),
(2026, 12, 18, '†) Sf. Cuv. Daniil Sihastrul; Sf. Mc. Sebastian și Zoe; Sf. Ier. Modest, arhiep. Ierusalimului', 'black'),
(2026, 12, 19, '† Sf. Cuv. Muceniță Evloghia de la Samurcășești; Sf. Mc. Bonifatie; Sf. Cuv. Aglaia, Sf. Ier. Grichentie, ep. Etiopiei;', 'black'),
(2026, 12, 20, 'Înainte-prăznuirea Nașterii Domnului; Sf. Sfințit Mc. Ignatie Teoforul, ep. Antiohiei; †) Sf. Cuv. Serafim cel Răbdător de la Sâmbăta de Sus', 'red'),
(2026, 12, 21, 'Sf. Mc. Iuliana din Nicomidia; Sf. Mc. Temistocle', 'black'),
(2026, 12, 22, '†) Sf. Ier. Petru Movilă, mitr. Kievului; Sf. M. Mc. Anastasia', 'black'),
(2026, 12, 23, '† Sf. Cuv. Antonina de la Tismana ; Sf. 10 Mc. din Creta; Sf. Ier. Pavel, arhiep. Neocezareei', 'black'),
(2026, 12, 24, 'Sf. Mc. Eugenia', 'black'),
(2026, 12, 25, '(†) Nașterea Domnului (Crăciunul)', 'red'),
(2026, 12, 26, 'A doua zi de Crăciun; †) Soborul Maicii Domnului; †) Sf. Cuv. Nicodim cel Sfințit de la Tismana; †) Sf. Cuv. Mc. Gherasim de la Tismana; Sf. Sfințit Mc. Eftimie, ep. Sardelor', 'red'),
(2026, 12, 27, 'A treia zi de Crăciun; † Sf. Ap., întâiul Mc. și arhid. Ștefan; Sf. Cuv. Teodor Mărt.', 'red'),
(2026, 12, 28, 'Sf. 20.000 de Mc. arși în Nicomidia', 'black'),
(2026, 12, 29, 'Sf. 14.000 de prunci uciși din porunca lui Irod; Sf. Cuv. Marcel și Tadeu', 'black'),
(2026, 12, 30, 'Sf. Mc. Anisia fecioara; Sf. Cuv. Teodora din Cezareea; Sf. Cuv. Leon, arhim.', 'black'),
(2026, 12, 31, 'Odovania Praznicului Nașterii Domnului; Sf. Cuv. Melania Romana; † Sf. Mc. Hermes', 'black')
ON CONFLICT (year, month, day_number) DO UPDATE SET description = EXCLUDED.description, color = EXCLUDED.color;